---
title: "commencing boot sequence"
date: 2025-12-22
author: hrmnjt
---

Hello world!

Boot Sequence is the set of instructions that get the computers running when
power button is pressed. I don't know how it goes for MacOS or Windows but in
Linux distro this means BIOS starting up Master Boot Record (MBR), which runs
GRUB, which executes linux kernel, which executes init sequence, which executes
runlevel programs. (There is a lot of hand-waving here). The point here is that
this post signifies something similar for my blogging journey.

This is not the first time I've done this. I've tried my hand at blogging
earlier in 2019, 2021, 2024 but I didn't blog that often. It is a function of
how bored I was at work and how much free time I had at hand after I had
exhausted myself on my office-job. Generally, this would mean I would encounter
an interesting topic (at least interesting to me) on which I would have an
opinion, will take a backseat because of trying to solve the actual problem
and not cutting off from work completely. The topic would be a mid-attempt at a
post or end up in whatever-todos-methodology I'm trying out to be more
productive.

Another reason I didn't stick to blogging attempts have been my choice of
tooling or rather the paradox of choice I've had for tooling. I've been very
opinionated about hosting platform, SSG, theme or domain configuration and
instead of focusing on expressing myself I've always been tinkering with tooling
and making it "perfect" for me to be productive and express my style to the
world and to internet. For record, I went from Hugo on Github Pages, theme
shopping for Hugo, forking and tweaking the theme continiously to add or
substract features, Zola with Github Pages, Zola with my-custom-minimal-noJS
theme, back to Hugo with my-custome-minimal-noJS theme, and trying Cloudflare
Pages, and so on. I learnt a lot about SSGs, how they work, how to customize
them to the most minute level, even internals about templating languages and
what it takes to create a theme from scratch. However, this is a distraction
from my usual day-to-day worka nd I can only keep up with web-dev for so long
before I churn back into fixing my work problems.

2024 and 2025 have been amazing years for me personally and professionally. (a) 
Our family grew with addition of Leo (foster-fail doggo) and Sufi (daughter).
(b) I quit my 7-year old job to join a new org (c) moved from Dubai to Abu
Dhabi (d) read and learned a lot about everything that matters and what doesn't
matter. My personality is a lot different since all of this happened; and my
approach to reading, writing and thinking has changed a lot since last year. Two
takeaways (of the many reflections) that are relevant in this context:
- Nobody cares about my blog; or how it looks; or how performant it is (other
than me)
- I learn a lot more about a topic when I write notes

I've been maintaining a worklog (neovim markdown scratch notes for work-stuff)
since 2022 daily. My problem solving approach is to write notes, break down the
problem, and zoom-in or out to understand it better and even explain it better
to peers and leadership. This has paid me 10x of how much effort I've put
into writing notes. It has convinved me about journaling. Or putting my thoughts
on proverbial paper. I wanted to give myself another chance with my blogging, to
think better, to learn in public, to leave breadcrumbs for trace my thoughts and
to iterate over my thoughts. I'm a bit hesitant about this but I've read enough
success stories about this and want this to work for me.

I started writing this post because I wanted to write the first post to try out
how this new blog looks. It has been the quickest post I've ever written (20m
on my timer). Onwards and upwards.

EOF.
